version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: personal_planner_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: orifjon13
      POSTGRES_DB: specific_planner_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
